# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/workspace/oceanbase;/workspace/oceanbase")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "server;sql-parser;libs")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "OceanBase")
set(CPACK_DEBIAN_PACKAGE_NAME "oceanbase-ce")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "Optional")
set(CPACK_DEBIAN_PACKAGE_RELEASE "ubuntu22.04")
set(CPACK_DEBIAN_PACKAGE_SECTION "database")
set(CPACK_DEBIAN_SERVER_DEBUGINFO_PACKAGE "ON")
set(CPACK_DEBIAN_SERVER_PACKAGE_CONTROL_EXTRA "/workspace/oceanbase/tools/systemd/profile/postinst;/workspace/oceanbase/tools/systemd/profile/prerm;/workspace/oceanbase/tools/systemd/profile/postrm")
set(CPACK_DEBIAN_SERVER_PACKAGE_DEPENDS "oceanbase-ce-libs (= 4.3.3.0-ubuntu22.04), jq, systemd")
set(CPACK_DEBIAN_SERVER_PACKAGE_NAME "oceanbase-ce")
set(CPACK_DEB_COMPONENT_INSTALL "ON")
set(CPACK_DEB_MAIN_COMPONENT "server")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/workspace/oceanbase/deps/3rd/usr/local/oceanbase/devtools/share/cmake-3.22/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "OceanBase_CE built using CMake")
set(CPACK_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INSTALLED_DIRECTORIES "/workspace/oceanbase;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME "oceanbase-ce 4.3.3.0")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "oceanbase-ce 4.3.3.0")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "/workspace/oceanbase/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "https://open.oceanbase.com/")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "OceanBase is a distributed relational database")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/workspace/oceanbase/deps/3rd/usr/local/oceanbase/devtools/share/cmake-3.22/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "OceanBase is a distributed relational database")
set(CPACK_PACKAGE_FILE_NAME "oceanbase-ce-4.3.3.0-Source")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://open.oceanbase.com/")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "oceanbase-ce 4.3.3.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "oceanbase-ce 4.3.3.0")
set(CPACK_PACKAGE_NAME "oceanbase-ce")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "OceanBase Inc.")
set(CPACK_PACKAGE_VERSION "4.3.3.0")
set(CPACK_PACKAGE_VERSION_MAJOR "4")
set(CPACK_PACKAGE_VERSION_MINOR "3")
set(CPACK_PACKAGE_VERSION_PATCH "3")
set(CPACK_PACKAGING_INSTALL_PREFIX "/home/admin/oceanbase")
set(CPACK_RESOURCE_FILE_LICENSE "/workspace/oceanbase/deps/3rd/usr/local/oceanbase/devtools/share/cmake-3.22/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/workspace/oceanbase/deps/3rd/usr/local/oceanbase/devtools/share/cmake-3.22/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/workspace/oceanbase/deps/3rd/usr/local/oceanbase/devtools/share/cmake-3.22/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/workspace/oceanbase;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/workspace/oceanbase/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "oceanbase-ce-4.3.3.0-Source")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux-Source")
set(CPACK_WIX_SIZEOF_VOID_P "")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/workspace/oceanbase/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
