# CMake generated Testfile for 
# Source directory: /workspace/oceanbase/unittest/storage/blocksstable
# Build directory: /workspace/oceanbase/unittest/storage/blocksstable
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_block_manager]=] "test_block_manager")
set_tests_properties([=[test_block_manager]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;2;storage_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;0;")
add_test([=[test_block_sstable_struct]=] "test_block_sstable_struct")
set_tests_properties([=[test_block_sstable_struct]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;3;storage_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;0;")
add_test([=[test_data_buffer]=] "test_data_buffer")
set_tests_properties([=[test_data_buffer]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;4;storage_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;0;")
add_test([=[test_index_block_aggregator]=] "test_index_block_aggregator")
set_tests_properties([=[test_index_block_aggregator]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;5;storage_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;0;")
add_test([=[test_tmp_file]=] "test_tmp_file")
set_tests_properties([=[test_tmp_file]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;7;storage_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;0;")
add_test([=[test_sstable_meta]=] "test_sstable_meta")
set_tests_properties([=[test_sstable_meta]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;9;storage_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;0;")
add_test([=[test_row_reader]=] "test_row_reader")
set_tests_properties([=[test_row_reader]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;12;storage_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;0;")
add_test([=[test_micro_block_reader]=] "test_micro_block_reader")
set_tests_properties([=[test_micro_block_reader]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;14;storage_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;0;")
add_test([=[test_micro_block_writer]=] "test_micro_block_writer")
set_tests_properties([=[test_micro_block_writer]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;15;storage_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;0;")
add_test([=[test_ref_cnt]=] "test_ref_cnt")
set_tests_properties([=[test_ref_cnt]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;20;storage_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;0;")
add_test([=[test_macro_block_id]=] "test_macro_block_id")
set_tests_properties([=[test_macro_block_id]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;21;storage_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;0;")
add_test([=[test_agg_row_struct]=] "test_agg_row_struct")
set_tests_properties([=[test_agg_row_struct]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;23;storage_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;0;")
add_test([=[test_skip_index_filter]=] "test_skip_index_filter")
set_tests_properties([=[test_skip_index_filter]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;24;storage_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;0;")
add_test([=[test_sstable_index_filter]=] "test_sstable_index_filter")
set_tests_properties([=[test_sstable_index_filter]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;25;storage_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;0;")
add_test([=[test_data_store_desc]=] "test_data_store_desc")
set_tests_properties([=[test_data_store_desc]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;26;storage_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;0;")
add_test([=[test_datum_rowkey_vector]=] "test_datum_rowkey_vector")
set_tests_properties([=[test_datum_rowkey_vector]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;27;storage_unittest;/workspace/oceanbase/unittest/storage/blocksstable/CMakeLists.txt;0;")
subdirs("encoding")
subdirs("cs_encoding")
