# CMake generated Testfile for 
# Source directory: /workspace/oceanbase/unittest/share
# Build directory: /workspace/oceanbase/unittest/share
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_scanner]=] "test_scanner")
set_tests_properties([=[test_scanner]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;2;storage_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_log_file_handler]=] "test_log_file_handler")
set_tests_properties([=[test_log_file_handler]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;11;storage_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_obj_cast]=] "test_obj_cast")
set_tests_properties([=[test_obj_cast]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;12;storage_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_datum_cmp]=] "test_datum_cmp")
set_tests_properties([=[test_datum_cmp]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;13;storage_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_ob_tg_mgr]=] "test_ob_tg_mgr")
set_tests_properties([=[test_ob_tg_mgr]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;15;storage_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_storage_file]=] "test_storage_file")
set_tests_properties([=[test_storage_file]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;16;storage_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_cluster_id_hash_conflict]=] "test_cluster_id_hash_conflict")
set_tests_properties([=[test_cluster_id_hash_conflict]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;17;storage_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_dag_scheduler]=] "test_dag_scheduler")
set_tests_properties([=[test_dag_scheduler]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;20;storage_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_dag_net_in_dag_scheduler]=] "test_dag_net_in_dag_scheduler")
set_tests_properties([=[test_dag_net_in_dag_scheduler]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;21;storage_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_debug_sync]=] "test_debug_sync")
set_tests_properties([=[test_debug_sync]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;40;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_ob_function]=] "test_ob_function")
set_tests_properties([=[test_ob_function]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;46;storage_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_ob_guard]=] "test_ob_guard")
set_tests_properties([=[test_ob_guard]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;47;storage_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_storage_device_manager]=] "test_storage_device_manager")
set_tests_properties([=[test_storage_device_manager]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;48;storage_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_tenant_resource]=] "test_tenant_resource")
set_tests_properties([=[test_tenant_resource]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;50;storage_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_ob_occam_timer]=] "test_ob_occam_timer")
set_tests_properties([=[test_ob_occam_timer]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;52;storage_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_ob_occam_thread_pool]=] "test_ob_occam_thread_pool")
set_tests_properties([=[test_ob_occam_thread_pool]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;53;storage_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_ob_future]=] "test_ob_future")
set_tests_properties([=[test_ob_future]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;55;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_ob_occam_time_guard]=] "test_ob_occam_time_guard")
set_tests_properties([=[test_ob_occam_time_guard]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;56;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_cluster_version]=] "test_cluster_version")
set_tests_properties([=[test_cluster_version]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;57;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_scn]=] "test_scn")
set_tests_properties([=[test_scn]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;58;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_tma_mgr]=] "test_tma_mgr")
set_tests_properties([=[test_tma_mgr]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;59;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_geo_bin]=] "test_geo_bin")
set_tests_properties([=[test_geo_bin]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;60;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_s2adapter]=] "test_s2adapter")
set_tests_properties([=[test_s2adapter]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;61;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_geo_common]=] "test_geo_common")
set_tests_properties([=[test_geo_common]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;62;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_wkt_parser]=] "test_wkt_parser")
set_tests_properties([=[test_wkt_parser]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;63;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_geo_3d]=] "test_geo_3d")
set_tests_properties([=[test_geo_3d]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;64;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_geo_tree]=] "test_geo_tree")
set_tests_properties([=[test_geo_tree]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;65;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_geo_srs]=] "test_geo_srs")
set_tests_properties([=[test_geo_srs]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;66;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_geo_srs_parser]=] "test_geo_srs_parser")
set_tests_properties([=[test_geo_srs_parser]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;67;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_geo_func_difference]=] "test_geo_func_difference")
set_tests_properties([=[test_geo_func_difference]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;68;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_geo_func_union]=] "test_geo_func_union")
set_tests_properties([=[test_geo_func_union]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;69;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_geo_func_box]=] "test_geo_func_box")
set_tests_properties([=[test_geo_func_box]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;70;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_throttling_utils]=] "test_throttling_utils")
set_tests_properties([=[test_throttling_utils]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;71;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_roaringbitmap]=] "test_roaringbitmap")
set_tests_properties([=[test_roaringbitmap]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;72;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_json_base]=] "test_json_base")
set_tests_properties([=[test_json_base]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;74;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_json_bin]=] "test_json_bin")
set_tests_properties([=[test_json_bin]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;75;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_json_path]=] "test_json_path")
set_tests_properties([=[test_json_path]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;76;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_json_schema]=] "test_json_schema")
set_tests_properties([=[test_json_schema]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;77;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_json_tree]=] "test_json_tree")
set_tests_properties([=[test_json_tree]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;78;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_text_analyzer]=] "test_text_analyzer")
set_tests_properties([=[test_text_analyzer]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;80;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_ash_index]=] "test_ash_index")
set_tests_properties([=[test_ash_index]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/share/CMakeLists.txt;92;ob_unittest;/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
subdirs("allocator")
subdirs("auto_increment")
subdirs("cache")
subdirs("client_feedback")
subdirs("deadlock")
subdirs("backup")
subdirs("schema")
subdirs("interrupt")
subdirs("tablet")
subdirs("location_cache")
subdirs("detect")
subdirs("vector")
subdirs("index_usage")
subdirs("compaction")
