# CMake generated Testfile for 
# Source directory: /workspace/oceanbase/unittest/storage
# Build directory: /workspace/oceanbase/unittest/storage
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_io_manager]=] "test_io_manager")
set_tests_properties([=[test_io_manager]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;43;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_iocb_pool]=] "test_iocb_pool")
set_tests_properties([=[test_iocb_pool]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;44;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_ob_col_map]=] "test_ob_col_map")
set_tests_properties([=[test_ob_col_map]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;45;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_placement_hashmap]=] "test_placement_hashmap")
set_tests_properties([=[test_placement_hashmap]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;46;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_parallel_external_sort]=] "test_parallel_external_sort")
set_tests_properties([=[test_parallel_external_sort]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;47;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_i_store]=] "test_i_store")
set_tests_properties([=[test_i_store]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;48;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_sstable_merge_info_mgr]=] "test_sstable_merge_info_mgr")
set_tests_properties([=[test_sstable_merge_info_mgr]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;49;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_sample_filter]=] "test_sample_filter")
set_tests_properties([=[test_sample_filter]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;50;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_tenant_tablet_stat_mgr]=] "test_tenant_tablet_stat_mgr")
set_tests_properties([=[test_tenant_tablet_stat_mgr]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;53;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_tenant_compaction_mem_pool]=] "test_tenant_compaction_mem_pool")
set_tests_properties([=[test_tenant_compaction_mem_pool]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;54;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_compaction_memory_context]=] "test_compaction_memory_context")
set_tests_properties([=[test_compaction_memory_context]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;55;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_handle_cache]=] "test_handle_cache")
set_tests_properties([=[test_handle_cache]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;57;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_hash_performance]=] "test_hash_performance")
set_tests_properties([=[test_hash_performance]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;59;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_row_fuse]=] "test_row_fuse")
set_tests_properties([=[test_row_fuse]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;60;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_query_engine]=] "test_query_engine")
set_tests_properties([=[test_query_engine]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;65;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_mvcc_callback]=] "test_mvcc_callback")
set_tests_properties([=[test_mvcc_callback]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;67;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_mds_list]=] "test_mds_list")
set_tests_properties([=[test_mds_list]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;69;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_mds_node]=] "test_mds_node")
set_tests_properties([=[test_mds_node]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;70;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_mds_table]=] "test_mds_table")
set_tests_properties([=[test_mds_table]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;73;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_mds_table_flush]=] "test_mds_table_flush")
set_tests_properties([=[test_mds_table_flush]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;74;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_mds_table_flusher]=] "test_mds_table_flusher")
set_tests_properties([=[test_mds_table_flusher]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;75;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_mds_dump_kv]=] "test_mds_dump_kv")
set_tests_properties([=[test_mds_dump_kv]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;76;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_mds_table_handle]=] "test_mds_table_handle")
set_tests_properties([=[test_mds_table_handle]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;80;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_is_old_mds]=] "test_is_old_mds")
set_tests_properties([=[test_is_old_mds]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;81;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_fixed_size_block_allocator]=] "test_fixed_size_block_allocator")
set_tests_properties([=[test_fixed_size_block_allocator]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;82;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_dag_warning_history]=] "test_dag_warning_history")
set_tests_properties([=[test_dag_warning_history]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;83;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_storage_schema]=] "test_storage_schema")
set_tests_properties([=[test_storage_schema]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;84;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_checkpoint_diagnose]=] "test_checkpoint_diagnose")
set_tests_properties([=[test_checkpoint_diagnose]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;85;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_tenant_meta_obj_pool]=] "test_tenant_meta_obj_pool")
set_tests_properties([=[test_tenant_meta_obj_pool]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;88;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_tablet_pointer_map]=] "test_tablet_pointer_map")
set_tests_properties([=[test_tablet_pointer_map]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;89;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_fts_plugin]=] "test_fts_plugin")
set_tests_properties([=[test_fts_plugin]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;30;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;90;storage_fts_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_storage_logger_manager]=] "test_storage_logger_manager")
set_tests_properties([=[test_storage_logger_manager]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;91;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_storage_log_read_write]=] "test_storage_log_read_write")
set_tests_properties([=[test_storage_log_read_write]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;92;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_storage_log_replay]=] "test_storage_log_replay")
set_tests_properties([=[test_storage_log_replay]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;93;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_linked_macro_block]=] "test_linked_macro_block")
set_tests_properties([=[test_linked_macro_block]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;94;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_tablet_dumped_medium_info]=] "test_tablet_dumped_medium_info")
set_tests_properties([=[test_tablet_dumped_medium_info]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;95;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_backup_utils]=] "test_backup_utils")
set_tests_properties([=[test_backup_utils]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;98;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_backup_tmp_file]=] "test_backup_tmp_file")
set_tests_properties([=[test_backup_tmp_file]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;99;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_backup_data_struct]=] "test_backup_data_struct")
set_tests_properties([=[test_backup_data_struct]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;100;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_backup_index_cache]=] "test_backup_index_cache")
set_tests_properties([=[test_backup_index_cache]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;101;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_backup_iterator]=] "test_backup_iterator")
set_tests_properties([=[test_backup_iterator]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;102;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_backup_index_merger]=] "test_backup_index_merger")
set_tests_properties([=[test_backup_index_merger]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;103;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_backup_extern_info_mgr]=] "test_backup_extern_info_mgr")
set_tests_properties([=[test_backup_extern_info_mgr]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;104;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_safe_destroy_handler]=] "test_safe_destroy_handler")
set_tests_properties([=[test_safe_destroy_handler]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;107;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_simple_rows_merger]=] "test_simple_rows_merger")
set_tests_properties([=[test_simple_rows_merger]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;108;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_global_iterator_pool]=] "test_global_iterator_pool")
set_tests_properties([=[test_global_iterator_pool]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;109;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_partition_incremental_range_spliter]=] "test_partition_incremental_range_spliter")
set_tests_properties([=[test_partition_incremental_range_spliter]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;110;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_partition_major_sstable_range_spliter]=] "test_partition_major_sstable_range_spliter")
set_tests_properties([=[test_partition_major_sstable_range_spliter]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;111;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_parallel_minor_dag]=] "test_parallel_minor_dag")
set_tests_properties([=[test_parallel_minor_dag]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;112;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_partition_range_splite]=] "test_partition_range_splite")
set_tests_properties([=[test_partition_range_splite]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;25;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;113;storage_dml_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_major_rows_merger]=] "test_major_rows_merger")
set_tests_properties([=[test_major_rows_merger]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;25;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;114;storage_dml_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_tablet]=] "test_tablet")
set_tests_properties([=[test_tablet]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;25;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;115;storage_dml_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_medium_list_checker]=] "test_medium_list_checker")
set_tests_properties([=[test_medium_list_checker]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;116;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_protected_memtable_mgr_handle]=] "test_protected_memtable_mgr_handle")
set_tests_properties([=[test_protected_memtable_mgr_handle]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;117;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_choose_migration_source_policy]=] "test_choose_migration_source_policy")
set_tests_properties([=[test_choose_migration_source_policy]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;118;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_sstable_log_ts_range_cut]=] "test_sstable_log_ts_range_cut")
set_tests_properties([=[test_sstable_log_ts_range_cut]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;128;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_co_sstable]=] "test_co_sstable")
set_tests_properties([=[test_co_sstable]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;129;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_co_sstable_rows_filter]=] "test_co_sstable_rows_filter")
set_tests_properties([=[test_co_sstable_rows_filter]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;130;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
add_test([=[test_compaction_iter]=] "test_compaction_iter")
set_tests_properties([=[test_compaction_iter]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;131;storage_unittest;/workspace/oceanbase/unittest/storage/CMakeLists.txt;0;")
subdirs("mockcontainer")
subdirs("transaction")
subdirs("tx")
subdirs("blocksstable")
subdirs("direct_load")
subdirs("utl_file")
subdirs("tx_table")
subdirs("ddl")
