# CMake generated Testfile for 
# Source directory: /workspace/oceanbase/unittest/logservice
# Build directory: /workspace/oceanbase/unittest/logservice
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_log_checksum]=] "test_log_checksum")
set_tests_properties([=[test_log_checksum]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;2;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;6;log_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_log_entry_and_group_entry]=] "test_log_entry_and_group_entry")
set_tests_properties([=[test_log_entry_and_group_entry]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;2;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;7;log_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_lsn]=] "test_lsn")
set_tests_properties([=[test_lsn]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;2;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;8;log_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_log_meta_entry_header]=] "test_log_meta_entry_header")
set_tests_properties([=[test_log_meta_entry_header]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;2;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;9;log_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_log_meta_info]=] "test_log_meta_info")
set_tests_properties([=[test_log_meta_info]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;2;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;10;log_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_log_meta_entry]=] "test_log_meta_entry")
set_tests_properties([=[test_log_meta_entry]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;2;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;11;log_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_log_meta]=] "test_log_meta")
set_tests_properties([=[test_log_meta]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;2;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;12;log_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_log_state_mgr]=] "test_log_state_mgr")
set_tests_properties([=[test_log_state_mgr]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_log_reconfirm]=] "test_log_reconfirm")
set_tests_properties([=[test_log_reconfirm]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;15;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_log_sliding_window]=] "test_log_sliding_window")
set_tests_properties([=[test_log_sliding_window]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;16;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_log_group_buffer]=] "test_log_group_buffer")
set_tests_properties([=[test_log_group_buffer]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;18;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_lsn_allocator]=] "test_lsn_allocator")
set_tests_properties([=[test_lsn_allocator]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;19;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_fixed_sliding_window]=] "test_fixed_sliding_window")
set_tests_properties([=[test_fixed_sliding_window]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;20;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_ob_election]=] "test_ob_election")
set_tests_properties([=[test_ob_election]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;23;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_ob_election_with_priority]=] "test_ob_election_with_priority")
set_tests_properties([=[test_ob_election_with_priority]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;24;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_ob_election_message_compat]=] "test_ob_election_message_compat")
set_tests_properties([=[test_ob_election_message_compat]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;25;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_ob_election_priority_seperate_blacklist]=] "test_ob_election_priority_seperate_blacklist")
set_tests_properties([=[test_ob_election_priority_seperate_blacklist]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;26;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_ob_election_message_compat2]=] "test_ob_election_message_compat2")
set_tests_properties([=[test_ob_election_message_compat2]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;27;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_ls_election_reference_info]=] "test_ls_election_reference_info")
set_tests_properties([=[test_ls_election_reference_info]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;29;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_ob_tuple]=] "test_ob_tuple")
set_tests_properties([=[test_ob_tuple]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;30;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_log_config_mgr]=] "test_log_config_mgr")
set_tests_properties([=[test_log_config_mgr]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;32;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_clear_up_tmp_files]=] "test_clear_up_tmp_files")
set_tests_properties([=[test_clear_up_tmp_files]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;33;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_log_dir_match]=] "test_log_dir_match")
set_tests_properties([=[test_log_dir_match]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;34;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_server_log_block_mgr]=] "test_server_log_block_mgr")
set_tests_properties([=[test_server_log_block_mgr]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;35;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_tablet_replay_executor]=] "test_tablet_replay_executor")
set_tests_properties([=[test_tablet_replay_executor]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;36;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_role_change_handler]=] "test_role_change_handler")
set_tests_properties([=[test_role_change_handler]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;2;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;37;log_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_log_mode_mgr]=] "test_log_mode_mgr")
set_tests_properties([=[test_log_mode_mgr]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;2;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;38;log_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_palf_throttling]=] "test_palf_throttling")
set_tests_properties([=[test_palf_throttling]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;39;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_net_standby_restore_source]=] "test_net_standby_restore_source")
set_tests_properties([=[test_net_standby_restore_source]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;40;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_log_external_storage_handler]=] "test_log_external_storage_handler")
set_tests_properties([=[test_log_external_storage_handler]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;41;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_log_external_storage_io_task]=] "test_log_external_storage_io_task")
set_tests_properties([=[test_log_external_storage_io_task]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;42;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_log_cache]=] "test_log_cache")
set_tests_properties([=[test_log_cache]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;43;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
add_test([=[test_log_io_utils]=] "test_log_io_utils")
set_tests_properties([=[test_log_io_utils]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;44;ob_unittest;/workspace/oceanbase/unittest/logservice/CMakeLists.txt;0;")
