# CMake generated Testfile for 
# Source directory: /workspace/oceanbase/unittest/storage/tx
# Build directory: /workspace/oceanbase/unittest/storage/tx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_simple_tx_commit]=] "test_simple_tx_commit")
set_tests_properties([=[test_simple_tx_commit]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;22;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;31;c2pc_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
add_test([=[test_dup_msg_tx_commit]=] "test_dup_msg_tx_commit")
set_tests_properties([=[test_dup_msg_tx_commit]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;22;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;32;c2pc_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
add_test([=[test_cycle_commit]=] "test_cycle_commit")
set_tests_properties([=[test_cycle_commit]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;22;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;33;c2pc_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
add_test([=[test_simple_tx_ctx]=] "test_simple_tx_ctx")
set_tests_properties([=[test_simple_tx_ctx]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;27;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;34;tx_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
add_test([=[test_ls_log_writer]=] "test_ls_log_writer")
set_tests_properties([=[test_ls_log_writer]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;27;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;35;tx_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
add_test([=[test_ob_trans_hashmap]=] "test_ob_trans_hashmap")
set_tests_properties([=[test_ob_trans_hashmap]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;27;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;36;tx_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
add_test([=[test_ob_black_list]=] "test_ob_black_list")
set_tests_properties([=[test_ob_black_list]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;38;storage_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
add_test([=[test_ob_tx_log]=] "test_ob_tx_log")
set_tests_properties([=[test_ob_tx_log]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;39;storage_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
add_test([=[test_ob_timestamp_service]=] "test_ob_timestamp_service")
set_tests_properties([=[test_ob_timestamp_service]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;40;storage_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
add_test([=[test_ob_trans_rpc]=] "test_ob_trans_rpc")
set_tests_properties([=[test_ob_trans_rpc]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;41;storage_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
add_test([=[test_ob_tx_msg]=] "test_ob_tx_msg")
set_tests_properties([=[test_ob_tx_msg]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;42;storage_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
add_test([=[test_undo_action]=] "test_undo_action")
set_tests_properties([=[test_undo_action]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;43;storage_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
add_test([=[test_ob_id_meta]=] "test_ob_id_meta")
set_tests_properties([=[test_ob_id_meta]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;44;storage_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
add_test([=[test_ob_standby_read]=] "test_ob_standby_read")
set_tests_properties([=[test_ob_standby_read]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;45;storage_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
add_test([=[test_ob_standby_read_transfer]=] "test_ob_standby_read_transfer")
set_tests_properties([=[test_ob_standby_read_transfer]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;46;storage_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
add_test([=[test_ob_trans_tlog]=] "test_ob_trans_tlog")
set_tests_properties([=[test_ob_trans_tlog]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;47;storage_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
add_test([=[test_dup_table_lease]=] "test_dup_table_lease")
set_tests_properties([=[test_dup_table_lease]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;50;storage_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
add_test([=[test_redo_submitter]=] "test_redo_submitter")
set_tests_properties([=[test_redo_submitter]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;52;storage_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
add_test([=[test_trans_callback_mgr_fill_redo]=] "test_trans_callback_mgr_fill_redo")
set_tests_properties([=[test_trans_callback_mgr_fill_redo]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;53;storage_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
add_test([=[test_misc]=] "test_misc")
set_tests_properties([=[test_misc]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/workspace/oceanbase/unittest/storage/CMakeLists.txt;14;ob_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;54;storage_unittest;/workspace/oceanbase/unittest/storage/tx/CMakeLists.txt;0;")
subdirs("it")
